"use client";

import { useState, useRef, useEffect } from "react";
import styles from "./page.module.css";

function useTheme() {
  const [theme, setTheme] = useState("light");
  useEffect(() => {
    const stored = localStorage.getItem("theme") || "light";
    setTheme(stored);
    document.documentElement.setAttribute("data-theme", stored);
  }, []);
  const toggle = () => {
    const next = theme === "light" ? "dark" : "light";
    setTheme(next);
    localStorage.setItem("theme", next);
    document.documentElement.setAttribute("data-theme", next);
  };
  return { theme, toggle };
}

// PDF generation (client-side only)
async function downloadPDF({ siteName, sector_name, url, groups, totalPassed, totalFailed, totalNa }) {
  const { jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 16;
  let y = margin;

  // ── Header ────────────────────────────────────────────────────────────────
  doc.setFillColor(17, 24, 39); // near-black
  doc.rect(0, 0, pageW, 36, "F");
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("UK Website Compliance Report", margin, 16);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(200, 200, 200);
  doc.text(`Generated by compliance.ishsitotombe.co.uk  ·  ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`, margin, 26);
  doc.text(`${url}`, pageW - margin, 26, { align: "right" });
  y = 44;

  // ── Site + sector ─────────────────────────────────────────────────────────
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 24, 39);
  doc.text(siteName || url, margin, y);
  y += 6;
  if (sector_name) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`Sector: ${sector_name}`, margin, y);
    y += 5;
  }

  // ── Summary bar ───────────────────────────────────────────────────────────
  y += 4;
  const barH = 14;
  const barW = pageW - margin * 2;
  const total = totalPassed + totalFailed + totalNa;
  const passW = total > 0 ? (totalPassed / total) * barW : 0;
  const failW = total > 0 ? (totalFailed / total) * barW : 0;
  const naW   = barW - passW - failW;
  doc.setFillColor(22, 163, 74);
  doc.roundedRect(margin, y, passW || 0.1, barH, 2, 2, "F");
  doc.setFillColor(185, 28, 28);
  doc.rect(margin + passW, y, failW, barH, "F");
  doc.setFillColor(209, 213, 219);
  doc.rect(margin + passW + failW, y, naW, barH, "F");
  // legend
  y += barH + 5;
  const dot = (cx, col) => { doc.setFillColor(...col); doc.circle(cx, y - 1.5, 2, "F"); };
  dot(margin + 2, [22, 163, 74]);
  doc.setFontSize(8); doc.setTextColor(17, 24, 39);
  doc.text(`${totalPassed} passed`, margin + 6, y);
  dot(margin + 34, [185, 28, 28]);
  doc.text(`${totalFailed} failed`, margin + 38, y);
  if (totalNa > 0) {
    dot(margin + 66, [150, 150, 150]);
    doc.text(`${totalNa} n/a`, margin + 70, y);
  }
  y += 8;

  // ── Per-group tables ───────────────────────────────────────────────────────
  const GROUP_META = {
    data_protection:  { label: "Data Protection & Privacy" },
    security_company: { label: "Security & Company Info" },
    consumer_law:     { label: "Consumer Law" },
    marketing:        { label: "Marketing & Advertising" },
    accessibility:    { label: "Accessibility" },
    sector_specific:  { label: "Sector-Specific" },
  };
  const GROUP_ORDER = ["data_protection", "security_company", "consumer_law", "marketing", "accessibility", "sector_specific"];

  for (const groupId of GROUP_ORDER) {
    const g = groups[groupId];
    if (!g || !g.done || g.checks.length === 0) continue;
    const meta = GROUP_META[groupId] || { label: groupId };

    // section header
    doc.setFillColor(243, 244, 246);
    doc.rect(margin, y, barW, 7, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(17, 24, 39);
    doc.text(meta.label, margin + 3, y + 5);
    y += 7;

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [["Status", "Check", "Law", "Severity", "Notes"]],
      body: g.checks.map(c => [
        c.pass === true ? "✓ Pass" : c.pass === false ? "✗ Fail" : "— N/A",
        c.label || "",
        c.law || "",
        c.severity ? c.severity.charAt(0).toUpperCase() + c.severity.slice(1) : "",
        c.explanation || "",
      ]),
      styles: { fontSize: 7.5, cellPadding: 2.5, overflow: "linebreak" },
      headStyles: { fillColor: [55, 65, 81], textColor: 255, fontStyle: "bold", fontSize: 7.5 },
      columnStyles: {
        0: { cellWidth: 14, fontStyle: "bold" },
        1: { cellWidth: 36 },
        2: { cellWidth: 22 },
        3: { cellWidth: 14 },
        4: { cellWidth: "auto" },
      },
      didParseCell(data) {
        if (data.column.index === 0 && data.section === "body") {
          const val = data.cell.raw;
          if (val.startsWith("✓")) data.cell.styles.textColor = [22, 163, 74];
          else if (val.startsWith("✗")) data.cell.styles.textColor = [185, 28, 28];
          else data.cell.styles.textColor = [100, 100, 100];
        }
        if (data.column.index === 3 && data.section === "body") {
          const v = data.cell.raw.toLowerCase();
          if (v === "high")   data.cell.styles.textColor = [185, 28, 28];
          if (v === "medium") data.cell.styles.textColor = [180, 83, 9];
        }
      },
      didDrawPage(data) { y = data.cursor.y; },
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `Results are indicative, not legal advice. Scans publicly visible HTML only.  ·  Page ${i} of ${pageCount}`,
      pageW / 2, doc.internal.pageSize.getHeight() - 8,
      { align: "center" }
    );
  }

  const filename = `compliance-report-${(siteName || url).replace(/[^a-z0-9]/gi, "-").toLowerCase()}.pdf`;
  doc.save(filename);
}

const EXAMPLES = [
  { label: 'Moonpig',      url: 'https://www.moonpig.com' },
  { label: 'Monzo',        url: 'https://monzo.com' },
  { label: 'Purplebricks', url: 'https://www.purplebricks.co.uk' },
];

const SEVERITY = {
  high:   { label: "High",   cls: "sevHigh"   },
  medium: { label: "Medium", cls: "sevMedium" },
  low:    { label: "Low",    cls: "sevLow"    },
};

const GROUP_META = {
  data_protection:  { icon: "🔒", label: "Data Protection & Privacy" },
  security_company: { icon: "🏢", label: "Security & Company Info" },
  consumer_law:     { icon: "⚖️",  label: "Consumer Law" },
  marketing:        { icon: "📣", label: "Marketing & Advertising" },
  accessibility:    { icon: "♿", label: "Accessibility" },
  sector_specific:  { icon: "🏷️",  label: "Sector-Specific" },
};


function CheckRow({ check, delay }) {
  const pass = check.pass;
  let statusCls, statusIcon, borderColor;
  if (pass === true)       { statusCls = "statusPass"; statusIcon = "✓"; borderColor = "#1a7a4a"; }
  else if (pass === false) { statusCls = "statusFail"; statusIcon = "✗"; borderColor = "#b91c1c"; }
  else                     { statusCls = "statusNa";   statusIcon = "—"; borderColor = "#d1d5db"; }

  const sev = SEVERITY[check.severity] || SEVERITY.low;

  return (
    <div className={`${styles.checkRow} fade-up`} style={{ borderLeftColor: borderColor, animationDelay: `${delay}ms` }}>
      <div className={`${styles.statusDot} ${styles[statusCls]}`}>{statusIcon}</div>
      <div className={styles.checkBody}>
        <div className={styles.checkHeader}>
          <span className={styles.checkLabel}>{check.label}</span>
          <span className={styles.lawTag}>{check.law}</span>
        </div>
        <p className={styles.checkExplanation}>{check.explanation}</p>
      </div>
      <span className={`${styles.sevBadge} ${styles[sev.cls]}`}>{sev.label}</span>
    </div>
  );
}

function GroupSection({ groupId, checks, isLoading, isError, errorMessage }) {
  const meta  = GROUP_META[groupId] || { icon: "•", label: groupId };
  const passed = checks.filter(c => c.pass === true).length;
  const failed = checks.filter(c => c.pass === false).length;
  const na     = checks.filter(c => c.pass === null).length;

  return (
    <div className={styles.groupSection}>
      <div className={styles.groupHeader}>
        <span className={styles.groupIcon}>{meta.icon}</span>
        <span className={styles.groupLabel}>{meta.label}</span>
        {isLoading && <span className={styles.groupSpinner} />}
        {!isLoading && !isError && checks.length > 0 && (
          <div className={styles.groupCounts}>
            {failed > 0 && <span className={styles.gcFail}>{failed} failed</span>}
            {passed > 0 && <span className={styles.gcPass}>{passed} passed</span>}
            {na > 0     && <span className={styles.gcNa}>{na} n/a</span>}
          </div>
        )}
        {isError && <span className={styles.groupErrorBadge}>error</span>}
      </div>

      {isError && (
        <p className={styles.groupErrorMsg}>⚠ {errorMessage}</p>
      )}

      {checks.length > 0 && (
        <div className={styles.checkList}>
          {checks.map((c, i) => <CheckRow key={c.id} check={c} delay={i * 35} />)}
        </div>
      )}
    </div>
  );
}

const GROUP_ORDER = ["data_protection", "security_company", "consumer_law", "marketing", "accessibility", "sector_specific"];

export default function ComplianceChecker() {
  const { theme, toggle } = useTheme();
  const [url, setUrl]           = useState("");
  const [loading, setLoading]   = useState(false);
  const [meta, setMeta]         = useState(null);
  const [groups, setGroups]     = useState({});
  const [auditDone, setAuditDone] = useState(false);
  const [error, setError]       = useState(null);
  const [pdfLoading, setPdfLoading] = useState(false);
  const abortRef = useRef(null);

  const reset = () => {
    abortRef.current?.abort();
    setMeta(null); setGroups({}); setAuditDone(false); setError(null); setUrl("");
  };

  const audit = async (target) => {
    let u = (target || url).trim();
    if (!u) return;
    if (!u.startsWith("http")) u = "https://" + u;

    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    setLoading(true);
    setError(null);
    setMeta(null);
    setAuditDone(false);
    if (target) setUrl(u);

    // Groups are initialised when the 'classified' chunk arrives with batch_ids
    setGroups({});

    try {
      const res = await fetch(process.env.NEXT_PUBLIC_AUDIT_API_URL, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: u }),
        signal: controller.signal,
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Something went wrong.");
      }

      const reader  = res.body.getReader();
      const decoder = new TextDecoder();
      let   buffer  = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop(); // keep incomplete last line

        for (const line of lines) {
          if (!line.trim()) continue;
          let chunk;
          try { chunk = JSON.parse(line); } catch { continue; }

          if (chunk.type === "meta") {
            setMeta(chunk);
          } else if (chunk.type === "classified") {
            setMeta(prev => ({ ...prev, sector: chunk.sector, sector_name: chunk.sector_name, batch_ids: chunk.batch_ids }));
            // Initialise exactly the groups that will run
            if (chunk.batch_ids?.length) {
              const initial = {};
              chunk.batch_ids.forEach(id => { initial[id] = { checks: [], done: false, error: null }; });
              setGroups(initial);
            }
          } else if (chunk.type === "group") {
            setGroups(prev => ({
              ...prev,
              [chunk.group_id]: { checks: chunk.checks, done: true, error: null },
            }));
          } else if (chunk.type === "group_error") {
            setGroups(prev => ({
              ...prev,
              [chunk.group_id]: { checks: [], done: true, error: chunk.message },
            }));
          } else if (chunk.type === "done") {
            setAuditDone(true);
          }
        }
      }
    } catch (e) {
      if (e.name !== "AbortError") setError(e.message || "Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const allChecks    = Object.values(groups).flatMap(g => g.checks);
  const totalPassed  = allChecks.filter(c => c.pass === true).length;
  const totalFailed  = allChecks.filter(c => c.pass === false).length;
  const totalNa      = allChecks.filter(c => c.pass === null).length;
  const groupsDone   = Object.values(groups).filter(g => g.done).length;
  const groupsTotal  = Object.keys(groups).length;
  const hasAnyResult = allChecks.length > 0 || groupsDone > 0;

  const handleDownloadPDF = async () => {
    setPdfLoading(true);
    try {
      await downloadPDF({
        siteName: meta?.site_name,
        sector_name: meta?.sector_name,
        url,
        groups,
        totalPassed,
        totalFailed,
        totalNa,
      });
    } finally {
      setPdfLoading(false);
    }
  };

  return (
    <main className={styles.main}>
      <nav className={styles.nav}>
        <a href="https://ishsitotombe.co.uk" className={styles.navBrand}>ish</a>
        <div className={styles.navRight}>
          <button className={styles.themeBtn} onClick={toggle} aria-label="Toggle theme">
            {theme === "light" ? "Dark" : "Light"}
          </button>
          <a href="https://ishsitotombe.co.uk" className={styles.navCta}>Get in touch</a>
        </div>
      </nav>

      <div className={styles.container}>
        {/* Hero */}
        <div className={styles.hero}>
          <span className={styles.tag}>Free tool · UK compliance</span>
          <h1 className={styles.heading}>Website compliance checker</h1>
          <p className={styles.subheading}>
            Full UK legal audit — GDPR, PECR, Companies Act, Consumer Rights Act, and more.
            Up to 260 checks across 21 industry categories. Results in under a minute.
          </p>
        </div>

        {/* Input */}
        <div className={styles.inputCard}>
          <div className={styles.inputRow}>
            <span className={styles.inputIcon}>↗</span>
            <input
              type="url"
              className={styles.input}
              value={url}
              onChange={e => setUrl(e.target.value)}
              onKeyDown={e => e.key === "Enter" && audit()}
              placeholder="https://yourbusiness.co.uk"
              disabled={loading}
            />
            <button
              className={styles.auditBtn}
              onClick={() => audit()}
              disabled={loading || !url.trim()}
            >
              {loading ? <span className={styles.spinner} aria-hidden="true" /> : "Run audit"}
            </button>
          </div>

          {!hasAnyResult && !loading && (
            <div className={styles.examples}>
              <span className={styles.examplesLabel}>Try an example:</span>
              {EXAMPLES.map(ex => (
                <button key={ex.url} className={styles.exampleBtn} onClick={() => audit(ex.url)}>
                  {ex.label}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Error */}
        {error && (
          <div className={styles.errorCard}>
            <span className={styles.errorIcon}>⚠</span>
            <p>{error}</p>
          </div>
        )}

        {/* Results area */}
        {(loading || hasAnyResult) && (
          <div className={styles.results}>

            {/* Results header */}
            <div className={styles.scoreCard}>
              <div className={styles.scoreInfo}>
                <p className={styles.siteName}>{meta?.site_name || url}</p>
                {meta?.sector_name && (
                  <span className={styles.sectorBadge}>{meta.sector_name}</span>
                )}

                {auditDone ? (
                  <div className={styles.scoreCounts}>
                    <span className={styles.countPass}>{totalPassed} passed</span>
                    <span className={styles.countFail}>{totalFailed} failed</span>
                    {totalNa > 0 && <span className={styles.countNa}>{totalNa} n/a</span>}
                  </div>
                ) : (
                  <p className={styles.progressLabel}>
                    {groupsDone} of {groupsTotal || '…'} categories checked
                    {meta?.total_checks ? ` · ${allChecks.length} / ${meta.total_checks} checks` : ""}
                  </p>
                )}
              </div>

              <div className={styles.scoreActions}>
                {auditDone && (
                  <button
                    className={styles.pdfBtn}
                    onClick={handleDownloadPDF}
                    disabled={pdfLoading}
                  >
                    {pdfLoading ? (
                      <><span className={styles.spinnerDark} aria-hidden="true" /> Generating…</>
                    ) : (
                      "⬇ Download report"
                    )}
                  </button>
                )}
                {hasAnyResult && (
                  <button className={styles.resetBtn} onClick={reset}>New audit</button>
                )}
              </div>
            </div>

            {/* Warnings */}
            {meta?.js_shell && (
              <div className={styles.warningCard}>
                <span className={styles.warningIcon}>⚠</span>
                <p>{meta.js_shell_reason}</p>
              </div>
            )}
            {meta?.fetch_warning && (
              <div className={styles.warningCard}>
                <span className={styles.warningIcon}>⚠</span>
                <p>{meta.fetch_warning}</p>
              </div>
            )}

            {/* Group sections */}
            <div className={styles.groupList}>
              {GROUP_ORDER.map(groupId => {
                const g = groups[groupId];
                if (!g) return null;
                return (
                  <GroupSection
                    key={groupId}
                    groupId={groupId}
                    checks={g.checks}
                    isLoading={!g.done}
                    isError={!!g.error}
                    errorMessage={g.error}
                  />
                );
              })}
            </div>

            {/* Footer CTA — only once all done */}
            {auditDone && (
              <div className={`${styles.footer} fade-up`}>
                <div className={styles.footerCta}>
                  <p>Issues found on <strong>{meta?.site_name}</strong>? I can fix them.</p>
                  <a href="https://ishsitotombe.co.uk" className={styles.ctaBtn} target="_blank" rel="noopener noreferrer">
                    Get in touch →
                  </a>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </main>
  );
}
